name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Runs daily for security scans

jobs:
  # Job 1: Build and Test
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Lint Code
        run: npm run lint

  # Job 2: Build and Push Docker Image
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test # This job runs after the build-and-test job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: pretinkya/my_project_image:latest

  # Job 3: Deploy to Kubernetes
  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: docker-build-and-push # This job runs after the docker-build-and-push job
    steps:
      - name: Set Up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Configure kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml

  # Job 4: Security Scans
  security-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run OWASP Dependency Check
        run: dependency-check --scan . --format HTML
      - name: Scan Docker Image
        run: docker scan pretinkya/my_project_image:latest
